### ISSUE TITLE
I have a place to see if this Host is market place or not

### ISSUE THREAD

**Issue by iphands** [RedHatInsights/inventory-schemas#47]
I would suggest a boolean:
- marketplace: true/false

Downstream of inventory applications will use this fact to enable Smart Management features w/o SM skus.

**Comment by gmcculloug** [comment]
Fixed in PR https://github.com/RedHatInsights/inventory-schemas/pull/52 `Add is_marketplace boolean field to system profile`

**Comment by iphands** [comment]
Yay!
