### ISSUE TITLE
I have a place to see which CCSP this host belongs to

### ISSUE THREAD

**Issue by iphands** [RedHatInsights/inventory-schemas#48]
I think this should be an enum

- AWS
- Azure
- GCP
- IBM Cloud
- Alibaba
- Other

Where "Other" can be used for small scale CCSP vendors.

**Comment by gmcculloug** [comment]
Work happening in https://github.com/RedHatInsights/insights-host-inventory/pull/877

**Comment by kruai** [comment]
We store this information in the `provider_type` field of Host objects.
